### ISSUE TITLE
Mat/Pat - Maternity leave - Length of leave

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1890] opened 2024-08-29 21:17 UTC
Tab -  Maternity leave - Length of leave

**AC**
- [x] Weeks cannot be greater than 17 or less than zero
- [x] If weeks is 0, days must be present and between 1-6 inclusive
- [x] if weeks is present, and days is present, days must be between 0-6
- [x] Weeks must be filled before going to next tab
- [x] After weeks is filled start and end date alert should appear

**Comment by fazil-ey** [comment] 2024-09-14 00:24
Link to script 
https://bcgov.sharepoint.com/:u:/r/teams/03991/Shared%20Documents/General/Selenium/Selenium%20Scripts/Maternity%20Parental%20L%26A/MaternityLengthOfLeave_1890.side?csf=1&web=1&e=rZtfKw

**Comment by ayushdamani** [comment] 2024-09-17 15:43
Tested and confirmed working!

**Comment by Stella-Archer** [comment] 2024-09-19 17:27
@fazil-ey  I'm getting a fail in what looks like the allowance info section - whuich seems super weird to me
<img width="1537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzdxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ee97fb3b1a3bf006d2a97c7ea60775731eca667/image.png" alt="image.png" />

<img width="955" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0hyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7df0edcc948237a01c8950fedbd0c6c4f91694e4/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment] 2024-11-19 23:26
Worked perfectly PO Approved & Closing ticket
<img width="1155" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzdQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91b8d03175d6e82f4ae3fb74cf60e046b3b48fdd/image.png" alt="image.png" />

**Closed** 2024-11-19 23:27 UTC
Labels: Mat/Pat, PO Approved
