### ISSUE TITLE
Cold/Flu: Pop-up for Secondary Contact

### ISSUE THREAD

**Issue by ca-liu** [bcgov/digital-journeys#1054] opened 2023-04-17 17:58 UTC
**User Story**
As a registrant, I am encouraged to enter a secondary contact in case of OOO or movement of roles. Screenshot below highlights the contacts section from the mockup:
![image.png](https://images.zenhubusercontent.com/63d039ffe477f5df944dbc73/58a742c0-acbe-4b34-9713-c0c7d8586eec)

<ins>Note</ins>: There is are Primary and Secondary contacts on a form. Please limit contacts to two (2)  per form.

Tooltip wording:
>In an event that we are unable to contact you, we strongly encourage entering a secondary contact. The secondary contact will only be contracted as back up for your work area

**Tasks**
- [ ] Create ~tooltip~ popup for Contacts section of the form

**Acceptance Criteria**
- ~Tooltip~ popup opens when I click the ? icon and closes when I click close or outside of the portal / modal
- ~Tooltip~ popup wording is as per requirements setforth above

**Comment by chriscaldwell-psa** [comment] 2023-04-27 20:57
@Andrew-Vargas-bcgov As per the instructions via the link below, I have added a tool-tip button which acts as a pop-up tool-tip.  If  you could test this Andrew, I would appreciate your eyes on this. I think this is the intended behavior requested.  Thanks Chris 
https://github.com/bcgov/digital-journeys/blob/main/docs/forms.md#reusable-popup

**Comment by ayushdamani** [comment] 2023-05-01 21:32
Tested and verified:
- Pop-up appears when clicked on the tool-tip button.
- The same disappears when clicked outside or on the 'ok' button.

![Screenshot 2023-05-01 143030.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/7a1b6fdb-736a-4c0f-adcf-c5651c60e8b3)

**Comment by Andrew-Vargas-bcgov** [comment] 2023-05-02 15:41
works :)

**Comment by Abuchana** [comment] 2023-05-03 16:23
@chriscaldwell-psa  is the screenshot above the actual wording that pops up in the system? If so, there is a grammar mistake in that there is an unnecessary "are" in the first sentence. 

Also, I'm not sure where we got the copy from but this is the wording Heather gave to us recently. “To help ensure your team gets the information they need, please include secondary contact information as back up for your work area."

I sent her a message to confirm which is correct and will let you know what changes need to be made, if any.

**Comment by Stella-Archer** [comment] 2023-05-03 16:48
I wonder why we need this pop up at all, should it not be associated with the 'secondary contact section and upfront text?
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/72a13881-d010-4071-848c-b7ab976e8eaf)

**Comment by Abuchana** [comment] 2023-05-03 17:24
I think to encourage them to fill it out but maybe the upfront section is enough, we need to check with Heather. I do know for sure that “To help ensure your team gets the information they need, please include secondary contact information as back up for your work area." is the wording she wants, not the text in red you show above.

**Comment by Stella-Archer** [comment] 2023-05-03 23:07
closing this ticket as it's not necessary any more

**Comment by Stella-Archer** [comment] 2023-05-09 18:54
The secondary Contact fields should NOT be mandatory could we remove the validation on them 
thx much sorry only caught this one this morning :(

**Comment by chriscaldwell-psa** [comment] 2023-05-10 18:47
The fields under the Worksite secondary contact panel have all been changed so that 'Required' Validation has been removed.  The fields are now NOT mandatory.

**Comment by Stella-Archer** [comment] 2023-05-15 19:14
@chriscaldwell-psa This is working great in DEV could you push it to TEST

**Comment by bhumin-fw** [comment] 2023-05-15 19:51
@chriscaldwell-psa I have deployed DEV form to TEST, you can review and do let me know if you have any details to share with me here.
@Stella-Archer It seems ready to test on TEST environment.

**Comment by chriscaldwell-psa** [comment] 2023-05-15 20:35
@Stella-Archer  Cold & Flu has now been deployed to test.

**Comment by Stella-Archer** [comment] 2023-05-15 22:16
Yay worked great in TESt. PO Approved. Closed

**Closed** 2023-05-15 22:16 UTC
Labels: MVP, PO Approved, Cold / Flu
