### ISSUE TITLE
Cold/Flu: Registering a clinic for a NEW worksite (Front end)

### ISSUE THREAD

**Issue by NassNK** [bcgov/digital-journeys#998] opened 2023-03-23 16:02 UTC
[Uploading... New Clinic.png]
**User Story**
“As a user wanting to register my worksite for a clinic, I did not find my worksite listed so I need to register it as new clinic worksite”

**Tasks**

- [ ] Build frontend section as follows - 

> * [ ] Heading section “ 2023 Influenza Worksite Registration” 
> 
> * [ ]  Section Divider
> 
> * [ ] Instructions text box: “You have chosen this option because your worksite was not listed and has never been registered for a clinic previously”
> 
> 
> * [ ]  Section Divider
> 
> * [ ]  Worksite Information fields: Street, Address, City, Postal code
> These fields are all text box fields and should have an asterisk to indicate that they are   mandatory to complete. 
> 
> 
> * [ ]  Section Divider
> 
> * [ ]  Worksite Contact fields: First Name, Last Name, Area Code, Phone Number, Ext, Email Address
> These fields are all text box fields and should have an asterisk to indicate that they are   mandatory to complete. 
> 
> 
> * [ ]  Section Divider
> 
> * [ ]  Secondary Worksite Contact fields: First Name, Last Name, Area Code, Phone Number, Ext, Email Address
> These fields are all text box fields.
> 
> 
> * [ ]  Section Divider
> 
> * [ ]  Text box field “ Number of Employees at Worksite
> 	This field should have an asterisk to indicate it is mandatory and the logic should be control to a 	 value entry only. 
> 
> * [ ]  Dropdown options “ Open/Closed” with description “ Is this an open or closed clinic?” 
> 
> * [ ]  Dropdown options “ Yes/No” with description “Will the team be relocating?” 
> 
> * [ ]  Text box field “ Special Instructions”  
> 
> 
> * [ ]  Section Divider
> 
> * [ ]  Action Button “Submit”

**Acceptance Criteria**
- [ ] All fields are there as described in the tasks section

**Comment by NassNK** [comment] 2023-03-23 16:06
[Uploading... New Clinic.png]

**Comment by ca-liu** [comment] 2023-03-23 16:19
[Uploading... tmp_731f520a-41f0-4180-b11c-86905aed9660.png]

**Comment by ca-liu** [comment] 2023-03-23 16:21
![IMG-20230321-WA0000.jpeg](https://images.zenhubusercontent.com/63d039ffe477f5df944dbc73/f29b9af5-46b1-4846-a4e2-79e118e15e8e)

**Comment by ca-liu** [comment] 2023-03-23 16:22
![Screenshot_20230323-092205.png](https://images.zenhubusercontent.com/63d039ffe477f5df944dbc73/04099f62-e0e0-43fb-90b1-00947fab8bc1)

**Comment by ca-liu** [comment] 2023-03-23 16:22
![Screenshot_20230323-092205.png](https://images.zenhubusercontent.com/63d039ffe477f5df944dbc73/04099f62-e0e0-43fb-90b1-00947fab8bc1)

**Comment by Abuchana** [comment] 2023-05-02 16:48
From Heather: 

Event: User searches their worksite and NO existing registrations come up.
What happens: include visible text

“There are currently no registered contacts at this worksite. We appreciate you registering as a worksite contact for this location.”![Cold and Flu.png](https://images.zenhubusercontent.com/6005ca03d883b372a058fe50/fae12d16-2b6b-412e-8f65-5d26c0726827)

I’m thinking the ^text^ could replace the text in the box (as shown below)?

**Comment by ayushdamani** [comment] 2023-05-03 21:14
Tested and confirmed the required changes ✔️
The visible text shows the updated wording.

![Screenshot 2023-05-03 141131.png](https://images.zenhubusercontent.com/63f54aecd19de9f18f88a815/9b2ec8c3-622a-493e-8ad8-79f4300561d0)

**Comment by Stella-Archer** [comment] 2023-05-04 16:55
I ran this by Heather, messaging looks good but could we:
1/ Message on top, button below it
2/ have the button read "Register your worksite"
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/7ed7c97a-da95-4bbd-867f-764ecd44cfda)

**Comment by chriscaldwell-psa** [comment] 2023-05-08 18:12
The label was changed by the forms designer (Chris), the info panels were added by Bhumin. Note: the component used for this conditional panel was coded by the devs using a Container Component, labelled 'Registered Clinics'  (that is hidden) within the form. The traditional info/alert box component was not used in this situation because of the logic that was required.  This functionality can be tested.

**Comment by Stella-Archer** [comment] 2023-05-09 18:47
Sweet! this looks fantastic thanks, moving to PO PO Approving & closing!
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/c427d387-dd35-4d37-a279-09f90dbb01e5)

**Closed** 2023-05-09 18:47 UTC
Labels: MVP, PO Approved, Cold / Flu
