### ISSUE TITLE
Telework: Jump down link to manager's sign off section

### ISSUE THREAD

**Issue by MeghanStothers** [bcgov/digital-journeys#205] opened 2022-04-04 19:17 UTC
When the manager follows the email link to review and approve the employee's submission, they will need a jump down link to avoid scrolling to the manager's sign off section

**Comment by schuyt** [comment] 2022-04-04 22:28
I think this is a duplicate of this story: 

https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/166

**Comment by MeghanStothers** [comment] 2022-05-25 21:53
We'll pause on this one until we:
1) carry out user testing and get feedback from manager about the scrolling to get to the bottom of the form
2) get direction from Policy team they'd like us to do this - they might want people to read all information about the policy
3) We explore other usability options to reduce scrolling

**Closed** 2022-05-26 19:41 UTC
Labels: dev - TES, Telework Agreement
