### ISSUE TITLE
SL Review - Post Submission Data hand-off to ODS

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#570] opened 2022-09-12 16:43 UTC
**User Story**
As an ADM, once I have filled in an application I want the data to be transmitted to ODS so that the SHRs have the most updated report to present to execs

**Tasks**
- [x] confirmation message to ADMs after clicking on the button (this is now addressed in ticket#621) 
- [x] Data on form submission gets transmitted to ODS

**Acceptance Criteria**
When the ADM is able to data in the SL form before the validation meeting and also able to come back make changes and re-submit again

**Comment by iman-jamali-fw** [comment] 2022-09-28 18:01
Hi Patrick @T854236,
Can you help me with this task of sending SL Review data to ODS?

Please let me know what you need from me to have this data stored in an ODS endpoint?

I'd imagine that you need a table of the fields (name, type, require/optional) from me? Maybe in an excel sheet like the one for Telework.

And do you think, similar to Telework, two endpoints for test and prod are good enough?

**Comment by T854236** [comment] 2022-09-28 18:26
@iman-jamali-fw 
Hi Iman,

yes please provide list of columns names, data types, length for each, allow nulls or not.  Excel sheet will work great.  Yes I think an endpoint to start for each environment should work.

**Comment by HasanSifat** [comment] 2022-09-28 21:05
Hi @iman-jamali-fw and @T854236 
The requirement to send data to ODS will remain unchanged. However, there might be a change in the requirement for a hard button. We plan on discussing this with Simen tomorrow morning about the current process map and how it may be implemented in the tool before you put in too much work on this. The fields and their responses are somewhat finalized and so you can go ahead make the spreadsheet. But as I said, the requirement to send data off to ODS for reporting still remains.

**Comment by iman-jamali-fw** [comment] 2022-09-29 02:04
@T854236  Here is the initial list of SL Review fields. I wasn't sure where to create a spreadsheet and how to show nested objects, so adding the values here. Feel free to update this as the form evolves. I'm not sure about length and allowing for nulls, maybe @simensma-fresh  can comment on that.

@HasanSifat The SL Review form v2 on DEV fields (API names) were updated with these names. I updated some of your logic to not break the validation with the new names. If you can , please check the form to see if everything works as before. Thanks

```json
{
  "applicationId": "string",
  "applicationStatus": "string",

  "employeeName": "string",
  "employeeNumber": "string",
  "employeePositionTitle": "string",
  "employeeWorkCity": "string",
  "ministry": "string",
  "division": "string",
  "branch": "string",
  "admSupervisorName": "string",
  "admSupervisorEmail": "string",

  "keyResponsibility1": "string",
  "doYouWantToAddAnotherResponsibility2": "string yes/no",
  "keyResponsibility2": "string",
  "doYouWantToAddAnotherResponsibility3": "string yes/no",
  "keyResponsibility3": "string",

  "keyAccomplishment1": "string",
  "doYouWantToAddAnotherAccomplishment2": "string yes/no",
  "keyAccomplishment2": "string",
  "doYouWantToAddAnotherAccomplishment3": "string yes/no",
  "keyAccomplishment3": "string",

  "expertiseAndSkillsAchieving": {
    "visionAndGoalSetting": "boolean",
    "serviceOutcomesForCitizensAndClients": "boolean",
    "designingStrategyAndStructure": "boolean",
    "creatingAndSupportingChange": "boolean",
    "solvingProblemsCreatively": "boolean",
    "innovation": "boolean"
  },
  "expertiseAndSkillsLeading": {
    "executivePresence": "boolean",
    "valuingDiversityAndInclusion": "boolean",
    "relationshipBuilding": "boolean",
    "collaboration": "boolean",
    "communication": "boolean",
    "conflictManagement": "boolean",
    "promotingEmpowerment": "boolean",
    "leadingLargeTeams": "boolean",
    "leadingVirtually": "boolean"
  },
  "expertiseAndSkillsSkillsAndKnowledge": {
    "indigenousRelationsAndReconciliation": "boolean",
    "intergovernmentalRelations": "boolean",
    "executiveBriefing": "boolean",
    "cabinetAndTreasuryBoardSubmissions": "boolean",
    "legislationRegulationsAndPolicy": "boolean",
    "negotiations": "boolean",
    "labourRelations": "boolean",
    "ethics": "boolean",
    "financialManagement": "boolean",
    "procurement": "boolean",
    "projectManagement": "boolean",
    "programDeliveryOperations": "boolean",
    "riskManagement": "boolean",
    "digitalInformationAndTechnology": "boolean",
    "other": "boolean"
  },
  "expertiseAndSkillsPleaseSpecifyOther": "string",
  "expertiseAndSkillsComments": "string",

  "LearningAndDevelopmentAchieving": {
    "visionAndGoalSetting": "boolean",
    "serviceOutcomesForCitizensAndClients": "boolean",
    "designingStrategyAndStructure": "boolean",
    "creatingAndSupportingChange": "boolean",
    "solvingProblemsCreatively": "boolean",
    "innovation": "boolean"
  },
  "LearningAndDevelopmentLeading": {
    "executivePresence": "boolean",
    "valuingDiversityAndInclusion": "boolean",
    "relationshipBuilding": "boolean",
    "collaboration": "boolean",
    "communication": "boolean",
    "conflictManagement": "boolean",
    "promotingEmpowerment": "boolean",
    "leadingLargeTeams": "boolean",
    "leadingVirtually": "boolean"
  },
  "LearningAndDevelopmentSkillsAndKnowledge": {
    "indigenousRelationsAndReconciliation": "boolean",
    "intergovernmentalRelations": "boolean",
    "executiveBriefing": "boolean",
    "cabinetAndTreasuryBoardSubmissions": "boolean",
    "legislationRegulationsAndPolicy": "boolean",
    "negotiations": "boolean",
    "labourRelations": "boolean",
    "ethics": "boolean",
    "financialManagement": "boolean",
    "procurement": "boolean",
    "projectManagement": "boolean",
    "programDeliveryOperations": "boolean",
    "riskManagement": "boolean",
    "digitalInformationAndTechnology": "boolean",
    "other": "boolean"
  },
  "LearningAndDevelopmentPleaseSpecifyOther": "string",
  "LearningAndDevelopmentComments": "string",

  "whenIsReady": "string",

  "summaryRecommendations": "string",

  "iHaveHadAConversationWithTheSeniorLeaderAboutTheContentInThisForm": "boolean",
  "iHaveValidatedThisSeniorLeaderReadinessToCompleteForAnExecutiveRole": "boolean",
  "admName": "string",
  "validationDate": "string date"
}

```

**Comment by T854236** [comment] 2022-09-29 15:58
@iman-jamali-fw @simensma-fresh 

Please let me know what you'll allow in the application for string length or do you want us to set to 50 characters for now.  For the string yes/no, can that use boolean on the endpoint?

**Comment by T854236** [comment] 2022-09-29 17:00
[SL_ODS Data mapping.xlsx](https://github.com/bcgov/digital-journeys/files/9677196/SL_ODS.Data.mapping.xlsx)

Please review attachment with some recommendations on the endpoint creations.

**Comment by HasanSifat** [comment] 2022-09-29 20:12
post submission, if the ADM goes back to the form and resubmits again, would it replace the existing data that was captured from the form?

**Comment by iman-jamali-fw** [comment] 2022-09-29 21:27
@T854236, The goal is to initially post the SL review submission to an endpoint. ADM can later come back to the same form submission and resubmit. The question is, how ODS can handle the subsequent edit to the original submission? Can you provide a put/patch version of the same endpint to somehow update by something like `applicationId`, or, we just post to the same endpoint, and you'll resolve the update on the ODS end if `applicationId` is the same?

**Comment by T854236** [comment] 2022-09-29 21:31
@iman-jamali-fw we can allow PUT for updates by applicationID if that is the unique identifier.

**Comment by Abuchana** [comment] 2022-10-04 16:19
[https://app.zenhub.com/files/439477060/2ef4d92e-4909-4e5e-a7aa-a04517530b97/download]

**Comment by fazil-ey** [comment] 2022-10-04 18:30
@iman-jamali-fw I have added the required fields along with data constraints for most fields to the [doc](https://bcgov.sharepoint.com/:x:/r/teams/03991/Shared%20Documents/SL%20Review/3.%20Technical%20Requirements/sl-review-data-mapping.xlsx?d=wffb040e6134940d39508aec334c1c2fe&csf=1&web=1&e=bfQdkc). We need to confirm a couple of things, but for the most part we should be good. Will keep you posted. 

(The document is in the SL review teams channel)

**Comment by iman-jamali-fw** [comment] 2022-10-05 16:39
Hi @T854236 (cc @fazil-ey),
Do ODS fields support variable character length? And what is the max character length?
There is a number of fields in the SL Review form that have a word limit, looking for a safe way to capture those fields in ODS.

**Comment by T854236** [comment] 2022-10-05 19:48
@iman-jamali-fw yes it can support varchar.  Is 5k characters enough?  Lower the better to minimize bandwidth.

**Comment by iman-jamali-fw** [comment] 2022-10-06 21:28
@fazil-ey How long do you want the text length to be based on the 5k limit @T854236 mentioned? Can you specify them on the Excel sheet?

**Comment by iman-jamali-fw** [comment] 2022-10-06 21:32
@HasanSifat This is ready for testing on DEV. You should be able to edit your submissions under the `applications` tab. Please note, for now, the data is sent to the Telework endpoint, once we have the data mapping confirmed, @T854236 can help us have an endpoint for SL Review.

**Comment by HasanSifat** [comment] 2022-10-11 23:20
tested fine in the SL review form for me. I could search for a particular user by typing. I think we can keep this in review till we get confirmation from Patrick that the endpoint for SL review has been made in ODS

**Comment by T854236** [comment] 2022-10-11 23:57
@HasanSifat can you confirm you are ok with the size limits on the data structure?  It appears maximum length for comments/text fields are 255 characters long as per the spreadsheet.

**Comment by HasanSifat** [comment] 2022-10-12 00:51
@T854236 I have reviewed the spreadsheet with Fazila and the data constraints for all the fields look okay to me. Although for the fields we are pre-populating in the personal information section, it would be good to know the constraints on the ODS side. I've put in a comment in the spreadsheet beside those fields and you can find it here- https://bcgov.sharepoint.com/:x:/t/03991/EeZAsP9JE9NAlQiuwzTBwv4BUz7f3a-bZVblCLxxoHpuGg?e=lVb94h

**Comment by T854236** [comment] 2022-10-12 02:04
@HasanSifat 
unfortunately it looks like that document is not shared.  I get the following message when I try to access via the link.
![image](https://user-images.githubusercontent.com/84544775/195231942-f8320098-1c1a-4728-ab95-7e1b061ecd6b.png)

**Comment by T854236** [comment] 2022-10-13 15:22
@HasanSifat @iman-jamali-fw 
[sl_review_mapping.xlsx](https://github.com/bcgov/digital-journeys/files/9778182/sl_review_mapping.xlsx)


Thank you, attached updated data structure based on your feedback.  A new endpoint has been added to the API service in DEV.  More info: https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_app_slreview_info/

**Comment by iman-jamali-fw** [comment] 2022-10-13 23:01
Thank you @T854236 
So to confirm, this endpoint will support post, put (by `applicationId`), and delete (by `applicationId`)?

I'll let you and @HasanSifat know once it's connected and ready for testing.

**Comment by T854236** [comment] 2022-10-14 00:40
@iman-jamali-fw 

Yes it is however I may need to modify the approach.  Because the endpoint exposes an object from ODS and data there will only stay for 1 day.  If we are looking to delete records, we will need to introduce another mechanism to actually delete a record.

Can you confirm that you need a delete function of records and not update or virtual deletes?

The challenge here is because you data only stays in ODS for maximum 24h as ETL processes will move it to the BI data warehouse.

**Comment by iman-jamali-fw** [comment] 2022-10-14 16:26
@T854236 I confirm that team wants the record to be (hard) deleted.

**Comment by T854236** [comment] 2022-10-14 17:26
@iman-jamali-fw @HasanSifat 

Do you have projections on how many records will be created per year?  Can you confirm how long the program will run this year?

**Comment by HasanSifat** [comment] 2022-10-14 21:05
@T854236 there will be around 150 ADMs using the form to nominate at least 2 or for some ADMs it can be 10 nominations/submissions. So I can forecast from the time of launch (Nov 15) to the closing deadline (Jan 27) there will be around 300-500 entries coming into the database.

**Comment by T854236** [comment] 2022-10-18 15:36
Hi @iman-jamali-fw, unfortunately no records in ODS.

I've made some changes to the endpoint to convert the tinyint to bool from ODS.  Can you try submitting again?

**Comment by iman-jamali-fw** [comment] 2022-10-18 16:22
@T854236 Thanks for updating the endpoint.

I just had a few tests. Unfortunately, the POST request failed with 500 errors and the PUT request failed with 403 errors. Can you check the errors on your side and let me know? Thank you

**Comment by T854236** [comment] 2022-10-18 16:34
@iman-jamali-fw 

Error from logs:

"date" : "2022-10-18T09:16:39-07:00",
    "code" : "200",
    "message" : "[HY000] Field 'employeeName' doesn't have a default value (1364)",
    "resource" : "/apiserver/api.rsc/Datamart_Telework_app_slreview_info",
    "pathinfo" : "/Datamart_Telework_app_slreview_info",

**Comment by T854236** [comment] 2022-10-18 16:44
@iman-jamali-fw 

also added columns: ldsk_humanResources, essk_humanResources
removed: admName

**Comment by iman-jamali-fw** [comment] 2022-10-18 16:48
@T854236 OK the error makes sense. I'll update the form and will test again in the evening after the testing session (planned for the afternoon) was finished. 

Also, I noticed the 403 errors for PUT requests were because `applicationId` was not sent.

**Comment by iman-jamali-fw** [comment] 2022-10-18 23:14
@T854236 Just sent a POST request and got no error. Can you please check to see if it is actually passed?

**Comment by iman-jamali-fw** [comment] 2022-10-19 14:37
@T854236 Just tried again and see a 500 error. I should have missed the error in the logs last evening. Can you share the error logs?
`*__checkpoint ⇢ 500 from POST https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/Datamart_Telework_app_slreview_info`

**Comment by T854236** [comment] 2022-10-19 14:50
@iman-jamali-fw 

A column was added in error, I removed it in ODS and API server.  Please try again.

Error logged:
  "error" : {
    "date" : "2022-10-19T07:35:57-07:00",
    "code" : "200",
    "message" : "[HY000] Field 'app_slreview_infocol' doesn't have a default value (1364)",
    "resource" : "/apiserver/api.rsc/Datamart_Telework_app_slreview_info",
    "pathinfo" : "/Datamart_Telework_app_slreview_info",
    "request"

**Comment by iman-jamali-fw** [comment] 2022-10-19 14:55
@T854236 No worries. I sent another one and don't see an error :)

**Comment by T854236** [comment] 2022-10-19 14:57
@iman-jamali-fw 

Confirmed I see a record.

![image](https://user-images.githubusercontent.com/84544775/196727545-f45c2378-c171-426e-8367-489a7d3bd6ca.png)

**Comment by iman-jamali-fw** [comment] 2022-10-19 15:02
Woo-hoo 🎉

@T854236 Can you confirm if the PUT and DELETE versions of that endpoint are in place?

**Closed** 2022-10-19 15:51 UTC
Labels: dev - TES, MVP, SL Review

**Comment by T854236** [comment] 2022-10-19 15:53
@iman-jamali-fw yes enabled with GET/POST/PUT/DELETE.
