### ISSUE TITLE
Mat/Pat - Bug - Parental leave start date validation

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1448] opened 2023-11-15 00:11 UTC
1. The validation message keeps changing
2. wrong validation message as well if you pick a date thats more than 2 months in advance

Validation message  keeps changing
video - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-11-14%20at%204.09.32%20PM.mov?csf=1&web=1&e=9PPiZL

Wrong message  - 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8046d72267836d96ee61223e81afa4f870297795/image.png)

**Comment by ayushdamani** [comment] 2023-11-24 15:53
Validation message updated! Thank you, Andrew!

**Comment by fazil-ey** [comment] 2023-11-24 19:03
We are still seeing this issue. Steps to reproduce - select a child's birth date 2-3 years ago and select todays date or date in the future. The validation message sometimes incorrectly changes to "you cannot select a dat ein the past"

**Comment by Andrew-Vargas-bcgov** [comment] 2023-11-30 23:10
now you will see all of the errors for the field. If you immediately select a date that is invalid, the messages will be a bit weird until you select a valid date.

**Comment by ayushdamani** [comment] 2023-12-01 16:18
Not able to reproduce the issue after trying Fazil's steps

**Comment by MeghanStothers** [comment] 2023-12-01 21:01
@Stella-Archer Are we okay to close this one or would you like to test with me this aft?

**Closed** 2023-12-01 23:43 UTC
Labels: Bug, Mat/Pat, MVP, PO Approved, Test failed
