### ISSUE TITLE
TELEWORK: Implementation date field is empty for certain use cases

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#518] opened 2022-08-18 16:25 UTC
Background: As a manager/supervisor getting new applications to come in from my employees, I can see the implementation date field to be empty
 
Steps to Reproduce: It has been difficult to reproduce this result as we don't have enough information from the user who flagged this bug. From the program team, we anticipated a possible workflow issue, 
 
Actual Behavior: inside the tool, when the manager is going into the "review applications" tab, the implementation date field is coming up as empty for certain use cases
 
Expected Behaviour: all date fields should be populated as this document is considered to be a legal agreement
 
Environment: PROD

**Comment by HasanSifat** [comment] 2022-08-18 20:43
![MicrosoftTeams-image (9).png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/34bab9cb-87db-4a7c-a6f9-bcb8fde49869)

**Comment by DonMoffatt** [comment] 2022-08-18 21:44
Chris and I tested the form in PROD at 2 p.m. PDT with all three use cases (Occasional, < 3 days, 3+ days) and all looked fine (no missing information) and the supervisor/manager interface had no missing.

**Comment by iman-jamali-fw** [comment] 2022-08-25 00:58
I was able to reproduce this on TEST (should happen in all environements).
@DonMoffatt @ccoldwell  (cc @simensma-fresh)

It's a timezone issue that happens if the employee and supervisor are in different time zones - at the time that their current date is one day off.
The date field in question has a validation rule that checks for the start date not being the past. The problem occurs when the supervisor opens a form at a different timezone that is already the next day. This will result in the field becoming empty as the validation rule let the date pass through.

I also noticed that the generated PDF has an empty date field. This should be the different timezone of the PDF-Generating-server and the client, only happens when the date in client and server are one day off.

I'll look deeper and will update this comment once learn more about this issue and the potential fixes.

**Comment by Stella-Archer** [comment] 2022-08-25 20:22
"Ask Karim"

**Comment by iman-jamali-fw** [comment] 2022-08-26 02:07
@Stella-Archer The issue is fixed on DEV and ready for testing.

How to reproduce the issue on TEST (which doesn't have the fix yet):
1. Submit a form
2. log in as the manager of the submitted form (or you could assign yourself as the manager in step 1)
3. Under `Review and Process Applications`, open your assigned submission and look for the `Date/duration of agreement`.
  3.1. If you view the submission on the same day you'll see the date as expected
  3.2. Come back to the same submission after one day, you'll see the reported issue, the date is empty.

You can repeat the same steps on DEV and compare the results.
Please note that this reported issue only occurs when a manager views a submission that is assigned to him/her.

**Comment by Stella-Archer** [comment] 2022-08-30 15:30
YAYAYAYA
this worked!
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/13342028-da67-46b1-91bb-93f9084d5481)
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/1d9937c3-9272-440b-8cf5-25997a60abb1)

**Comment by Abuchana** [comment] 2022-08-30 15:53
Hasan to take another look and work with Iman

**Comment by HasanSifat** [comment] 2022-08-30 15:56
Submission ID#6186 was submitted 17 hrs ago and the implementation date is coming up as empty in that submission. Not sure why this submission is coming up as empty ![MicrosoftTeams-image (14).png](https://images.zenhubusercontent.com/61e5b78d9a5a1eb2ba7a92c3/f89753e7-fe14-452d-afb1-0ea38f17b924)

**Comment by iman-jamali-fw** [comment] 2022-08-30 23:04
@HasanSifat @Stella-Archer It's now working again on DEV. I also move the changes to TEST so both are ready for the test :)

There were some recent changes on the date component on DEV that broke the fix. I reverted the changes (based on my working instance on my local) on DEV and then did the same on TEST. Both should work as expected.

**Comment by HasanSifat** [comment] 2022-08-30 23:22
I've just put in 2 test applications for Stella to review tomorrow.

**Comment by Stella-Archer** [comment] 2022-08-30 23:46
thanks @HasanSifat I will test in the AM

**Comment by Stella-Archer** [comment] 2022-08-31 15:47
Date shows up in both TEST and DEV good to move this to PROD

**Comment by Abuchana** [comment] 2022-08-31 15:49
Simen to move to Prod

**Comment by iman-jamali-fw** [comment] 2022-09-01 00:23
@Stella-Archer @HasanSifat  Moved to PROD. Ready for testing.

**Closed** 2022-09-06 15:37 UTC
Labels: bug, dev - TES, Telework Agreement, high priority
