### ISSUE TITLE
Cold/Flu: Add box to capture "Unit #" or "Suite #"

### ISSUE THREAD

**Issue by ayushdamani** [bcgov/digital-journeys#1594] opened 2024-02-01 17:29 UTC
**User Story**
Under "Worksite information" there should be a box to capture "Unit #" or "Suite #"
This then becomes another data collection point that needs to be reflected on the reporting in it's own column; alternatively, we make the current "Street Number" box, "Unit/suite and street number" or something similar.

**Tasks**
Devs need to consult Don for this ticket please.

**Acceptance Criteria**
Under "Worksite information" there should be a box to capture "Unit #" or "Suite #"

**Comment by DonMoffatt** [comment] 2024-02-08 00:19
I asked @mikeshitelus today to make these changes. His response by email was "I guess there will be change on the FORM side? If that’s the case the table schema, stored procedure and endpoints etc. all need to be changed. Thanks, Mike" I informed @Stella-Archer  and suggested that they work together on these changes (Stella to coordinate the form side).

**Comment by Stella-Archer** [comment] 2024-02-08 19:20
Check with Mike on additional field in work site data and field name used in form

**Comment by DonMoffatt** [comment] 2024-02-08 21:38
@Stella-Archer Karla has requested that you keep us in the loop on the development of the data dictionary for this project as she may want to give input on the contents: we are hoping to standardize data dictionaries. Also, please copy Sarah Miles on email communications that I am included on.

**Comment by Andrew-Vargas-bcgov** [comment] 2024-02-14 16:49
Stella to set up call with don and mike

**Comment by jerry-ey** [comment] 2024-02-15 18:45
Document for discussion:

Endpoint: 
https://digital-journeys-forms-flow-api-test.apps.silver.devops.gov.bc.ca/influenza/worksites_ministries?ministry_id=2

<img width="822" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXhpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--251da0599580e7d4398b5c48d1d16c7364e7f5e1/CleanShot%202024-02-15%20at%2010.45.19%402x.png" alt="CleanShot 2024-02-15 at 10.45.19@2x.png" />

**Comment by jerry-ey** [comment] 2024-02-21 17:29
@mikeshi-bcgov 

Hi Mike,
 
I hope you're doing well. I wanted to reach out to see if there are any updates on the ticket 1594 you've been working on for the current sprint. As we're nearing the end of February, I thought it would be a good time to touch base and ensure that everything is progressing smoothly.
 
Since you're on another team, I understand if there might be different priorities or challenges you're facing. However, it would be helpful for us to have an idea of where things stand, especially as we approach the end of the sprint.
 
If there's anything you need assistance with or any obstacles in your way, please feel free to let me know. We're here to support each other and ensure the successful completion of our respective tasks.
 
Looking forward to hearing from you soon.
 
Best regards,
 
Jerry

**Comment by jerry-ey** [comment] 2024-02-21 18:11
Got email from Mike.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUI3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bf4f87009bfbbab4480401cdc44074832456dc1/CleanShot%202024-02-21%20at%2010.10.55%402x.png" alt="CleanShot 2024-02-21 at 10.10.55@2x.png" />

**Comment by mikeshitelus** [comment] 2024-02-21 19:07
@jerry-ey 
Hi Jerry, field "unit_or_suite" has been added to table "worksites" on ODS TEST, data initialized for Ministries and Worksites, and 4 API endpoints have been updated accordingly, please have some test.

 For GET:
 https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_vw_worksites_ministries_joined/
 https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_worksites/

 For POST:
 https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_insert_worksite_registration/

 https://analytics-testapi.psa.gov.bc.ca/apiserver/api.rsc/ods_datamart_influenza_update_worksite_registration/

**Comment by jerry-ey** [comment] 2024-02-23 17:59
@ayushdamani  Please test, thanks. 

<img width="1085" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMitIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--791ca9d8edb5c60ee4507b5d02fb0834e5063485/CleanShot%202024-02-23%20at%2009.58.15%402x.png" alt="CleanShot 2024-02-23 at 09.58.15@2x.png" />

**Comment by ayushdamani** [comment] 2024-02-26 16:54
Unit # or suite # box functionality works great.
- The box is optional to fill
- Numbers and alphabets are working in the box
- Checked and confirmed that the box's contents are visible and same under the 'Submitted forms' tab

Moving to PO!

**Comment by Stella-Archer** [comment] 2024-03-02 00:51
looks great Jerry
However I wonder why we need to fill fields for province and Country should they not all be "BC" and "Canada"
@Augusteen-myeong could you check with heather to confirm this?
The unti piece is perfect so I'm going to PO and close the ticket we cold write a new one if Heather would like the Province/country field to be prefilled or non editable.
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea70f4e322dd4335e883ac5b5705ca59ac7b3336/image.png" alt="image.png" />

**Comment by Stella-Archer** [comment] 2024-03-04 22:07
@mikeshi-bcgov what is the new field name for unit/suite#?

**Comment by mikeshi-bcgov** [comment] 2024-03-04 22:15
@Stella-Archer schema for table "worksites" is:
worksites
(
   worksite_id int,
  unit_or_suite varchar(128),
  street_number varchar(128),
  street_name varchar(128),
  city varchar(128),
  province varchar(128),
  postal_code varchar(50),
  country varchar(128),
  place_id varchar(4000), -- this is not being used right now
  application_id int,
  date_updated datetime
)

**Comment by Stella-Archer** [comment] 2024-03-04 22:54
sweet thanks @mikeshi-bcgov  have updated the DD with this info https://bcgov.sharepoint.com/:x:/r/teams/03991/Shared%20Documents/Cold%20and%20Flu/2023%20Cold%20and%20Flu/3_Design/DD_Influenza_db.xlsx?d=w6314fb159a6b4b2290da8b34af8e6820&csf=1&web=1&e=4fkUHB

**Comment by Augusteen-myeong** [comment] 2024-03-04 23:32
@Stella-Archer - Heather confirmed that "Province" and "Country" can be auto-populated.

**Comment by Stella-Archer** [comment] 2024-03-26 00:29
front end is fine for this
<img width="1437" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejRMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcd4b66abd9410ec5081dda05bedc202d871aecc/image.png" alt="image.png" />

**Comment by jerry-ey** [comment] 2024-03-28 17:15
Tested on PRD after api deployment from Mike. Working fine.

<img width="1496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9kQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d62f0d93b8d130705b6ffb7d1bbb9f76d73ed8f/image.png" alt="image.png" />

**Comment by mikeshi-bcgov** [comment] 2024-03-28 17:18
Thanks Jerry, confirm received 1 registration application id = 88734

**Comment by Stella-Archer** [comment] 2024-04-09 02:49
PO and closing

**Closed** 2024-04-09 02:50 UTC
Labels: PO Approved, Cold / Flu
