### ISSUE TITLE
Mat/Pat - Bug - Syncing issue for partner email

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1537] opened 2024-01-04 18:36 UTC
Partner email is Review page does is not syncing with the tab. In review the email was empty even though a value was filled in the form

link - https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202024-01-03%20at%2011.51.51%20AM.mov?csf=1&web=1&e=1rE7au

**AC**
- [ ] All fields in review page should sync with the form tabs

**Comment by jerry-ey** [comment] 2024-01-08 18:35
@Stella-Archer I tested couple time on TEST, and can not reproduce the issue. Do you want to do a quick verify again?
My steps to test is
- Tab - Parental leave -Partners information: Add Meghan email and employee id
- Then go to Tab - Review: I can still see the email showing.

**Comment by ayushdamani** [comment] 2024-01-10 16:21
Followed the steps provided by Jerry - unable to reproduce the issue either

**Comment by Stella-Archer** [comment] 2024-01-10 16:35
Partner Info was correct and populated in both the review page and partner info page in TEST closing this ticket
SA

**Closed by Stella-Archer** 2024-01-10 16:36 UTC
Labels: Bug, Mat/Pat, MVP
