### ISSUE TITLE
TELEWORK: Can't upload files

### ISSUE THREAD

**Issue by Stella-Archer** [bcgov/digital-journeys#373] opened 2022-06-24 19:43 UTC
Background: In the TEST environment I can not upload .mgs files, I get a "unauthorized message' and can not continue processing the form
 
Steps to Reproduce: 
1/ respond to a request from a telework applicant asking for 3 or more days telework
2/ upload .msg file(test other file types that are allowed - Supported file types: .eml, .msg, .docx, .pdf, common image formats)
 
Actual Behavior: "unauthorized message' displayed and can not continue processing the form
 
Expected Behaviour: file should be uploaded and reviewer should be able to proceed with submitting their decision 
 
Environment: TEST

**Comment by Stella-Archer** [comment] 2022-06-24 19:46
![image.png](https://images.zenhubusercontent.com/61e5ab4a9a5a1e4bd27a92b8/53ecebcb-70e4-43d3-a531-6ef786e5a84b)

**Comment by iman-jamali-fw** [comment] 2022-06-29 13:42
The issue exists on TEST and PROD while working fine on DEV.
This issue causes by `form-flow-files`. After an investigation with @warrenchristian1telus , it is most probably due to its deployment differences on TEST and PROD compared to DEV.

**Comment by warrenchristian1telus** [comment] 2022-06-29 22:09
@DonMoffatt I don't have enough information to estimate this. We are not yet sure about the root cause. I would suspect that this will be resolved along with #384 as it should include synchronizing the deployments of dev, test and prod. For now, I will add that as a blocker for this issue, so that we can revisit after that is complete and verify this issue has been resolved.

**Comment by DonMof** [comment] 2022-06-29 22:15
Thanks for the update. We noticed today that quite a few tickets (~15 or more) were closed without being assigned to sprints or having estimates, which makes Hasan's analysis of our velocity less precise.

**Comment by warrenchristian1telus** [comment] 2022-06-29 22:15
@kkapoor-fresh Can you please verify that this issue is resolved once the deployment changes are complete? This is working as expected in dev, but not test or prod. I'm hoping the work from #384 will resolve this.

**Comment by warrenchristian1telus** [comment] 2022-06-29 22:34
@DonMof We can certainly go back and fill in the blanks. If we do retroactive estimates, they should be extra accurate. Of course, this will also take some time away from development. I am seeing 48 Closed issues without estimates, and 40 open issues. Although the bulk (33) are still New: 2 B Estimated. Also, I suspect some of them were open/closed due to duplication,  deciding not to implement, etc. Some are also Pull Requests, which could probably all be Estimated at a 1 for code review / approval.

**Comment by DonMof** [comment] 2022-06-29 22:38
I set the ones I found in closed for the last sprint to 3, just to have a number on them and get a better estimate. It's something we can discuss at standup tomorrow re. whether you want to refine that.

**Comment by Stella-Archer** [comment] 2022-07-14 23:12
Issue seems to be solved with the update :)

**Closed** 2022-07-15 15:48 UTC
Labels: bug, dev - TES, Telework Agreement, MVP
