### ISSUE TITLE
SL Review: Closing process; form lockouts after open period  

### ISSUE THREAD

**Issue by HasanSifat** [bcgov/digital-journeys#672] opened 2022-10-27 20:13 UTC
No action is required on the official lockout date. On the actual lockout date we need to complete the following actions - 

**AC**
On the actual form lockout date (on?)
- [x] Make the form unavailable to the keycloak group 
- [ ] All draft submissions for SL review gets deleted 
- [x] Do not allow new submissions
- [ ] Delete submitted forms (on a different date?) 
- [x] Syncing submission data between Digital Journeys and ODS

Points to consider-
If we want to give access to submitted forms after lockout, it can make things complicated. Up to 1-2 weeks in advance 

- What do we do about forms that were in draft, after SEPT 29 deadline?

- What do we do about submitted forms after SEPT 29 deadline?

- make custom group for late submitters and make form accessible to that group after SEPT 29 deadline, until OCTOBER 09

**Comment by HasanSifat** [comment] 2022-10-27 22:22
Update: Forms will be open till February 10th.

**Comment by Stella-Archer** [comment] 2023-05-02 16:52
Confirm with JL that form will be informally open til October 09 no separate keycloack group will be built

**Comment by MeghanStothers** [comment] 2023-05-18 18:48
Stella nd Meghan to direct to Jodi

**Comment by MeghanStothers** [comment] 2023-05-25 18:25
@Stella to double-check with Jodi that we do want to make sure ADMs/SL cannot access/see the form after October 6.

**Comment by Stella-Archer** [comment] 2023-09-21 16:23
Jodi asked: In the event we have any ministries unable to meet the hard October 6th deadline to get their SLR forms in we are wondering:
1.	How much time does the DJ team need in order to change the SLR turn off date?
2.	If the hard close date is delayed 2-3 weeks are there any ramifications to the DJ team and the data team?

**Comment by fazil-ey** [comment] 2023-09-21 18:52
@Stella-Archer to get the information needed on what needs to happen to new, submitted and draft forms and on what dates. If anything more than simply removing access and deleting the forms - it can require 2 weeks

**Comment by Stella-Archer** [comment] 2023-09-22 23:27
**UPDATE from conversation with Jodi:**
**Questions:** 
1/ Could we change LOCKOUT date from Oct 10 to the 23 or 30?

2/ Would it be complex to turn the key cloak group/form back on after we’ve closed it?

**ACTIONS:**
**Sept 29 - The SL Review will be ‘finished’ for participants**
Executives are informed it is ‘closed’ but no technical action needed
•	DJ form will still be live and available for the executive group to access, edit, submit for validations and final submit until form **LOCKOUT DATE**
•	Links still live on the TEAMS Channel

**Oct. 3 - Check Status of draft/submissions**
* [ ] Digital Journey DEV team creates a report of all submissions still in draft

**Oct. 6 (midnight) - MS Teams LOCKOUT DATE The SL Review grace period over**
* [ ] JODI takes link down from MS TEAMS site

**Oct.10 (1st thing in the am) - Digital Journeys  LOCKOUT DATE** 
Executive should longer see SL Review in their Digital Journey profile they cannot access, create new submissions, edit or submit nominations for validation or final submission
* [ ] Digital Journey DEV team makes the 
SL Review form unavailable to the executive KeyCloak group

**After Oct. 10 - Admin group (Jodi, Martha, Emma) is STILL active to view and print form**
All draft submissions for SL review gets deleted - JODI to confirm this is OK
* [ ] DJ Dev team will need to remove all SLR Drafts
Delete submitted forms (But not validated forms)
* [ ]  JODI to confirm – this might need to happen on a different date according to PIA/retention 
Delete submitted forms and validated forms
* [ ]  Jodi to confirm – check in with PIA the date may be some time in DEC

**Comment by iman-jamali-fw** [comment] 2023-10-05 15:56
Latest update:
SL form locks for ADMs on Oct 13

**Comment by fazil-ey** [comment] 2023-10-05 18:31
@Stella-Archer will update the ticket with the latest plan of action

**Comment by Stella-Archer** [comment] 2023-10-10 15:44
Last I heard from Jodi they where deciding on the **20/23**

**Comment by Stella-Archer** [comment] 2023-10-11 15:55
@iman-jamali-fw - Adding to the closing procedure: Syncing submissions between ODC & DGJ ensure the results are consistent

**Comment by MeghanStothers** [comment] 2023-10-12 15:54
Decision waiting from Jodi about close date of October 20

**Comment by Stella-Archer** [comment] 2023-10-13 21:18
**FINAL CLOSING dates and Procedure:**

**Oct. 20 (midnight) - MS Teams LOCKOUT DATE The SL Review grace period over**
* [ ] JODI takes link down from MS TEAMS site

**Oct. 23 (1st thing in the am) - Digital Journeys  LOCKOUT DATE** 
Executive should longer see SL Review in their Digital Journey profile they cannot access, create new submissions, edit or submit nominations for validation or final submission
* [ ] Digital Journey DEV team ( @bhumin-fw ) makes the SL Review form unavailable to the executive KeyCloak group
* [ ] Digital Journey DEV team ( @iman-jamali-fw ) works with TES and BI to sync submissions between ODC & DGJ ensure the results are consistent


**After Oct. 23 - Admin group (Jodi, Martha, Emma) is STILL active to view and print form**
All draft submissions for SL review get deleted - **JODI to confirm this is OK**

* [ ] DJ Dev team will Delete all SLR Drafts forms AND 
Delete ALL SLR submitted forms (**But not validated forms)**
_JODI to confirm – this might need to happen on a different date according to PIA/retention._

**Date TBD**
Delete submitted forms and validated forms
* [ ] DJ Dev team will Delete ALL validated forms
* [ ]  Jodi to confirm – check in with PIA the date may be some time in DEC

**Comment by Stella-Archer** [comment] 2023-10-18 15:36
Jodi asks about the 23 closing date: HOLD ON: I am thinking they might want to access their drafts. Is it possible to leave their access open but prohibit their ability to create a new form?

**Comment by Stella-Archer** [comment] 2023-10-30 22:54
Jodi report the Agriculture people can still access and have submissions in draft, they will be done on NOV 10

**Comment by bhumin-fw** [comment] 2023-10-31 01:34
@Stella-Archer correct, we didn't delete any SL drafts. So if draft is exist then they will be able to submit SL form but not able to create start new SL form.

**Comment by JodiLittle** [comment] 2023-10-31 15:57
@bhumin-fw correction: ADMs in Agriculture have been able to access the form and create new ones. 3 new files have been created since "lock down" and one more is expected. This came as a surprise. We have given them a deadline of Nov 10 to complete. Want to make sure the system will function as it should and also flag the issue as the lock down after the 20th didn't work.

**Comment by Stella-Archer** [comment] 2023-11-17 16:43
Now that Nov 10 has come and gone, and Agriculture team has submitted their final nominations Jodi has confirmed it is ok to:
- [ ] 1/ Lock SLR down completely for applicants **YES**
- [ ] 2/ Delete all SLR Drafts forms **YES**
- [ ] 3/ Delete ALL SLR submitted for validation forms (But not validated forms) **YES**
- [ ] 4/  Close this ticket **YES**

I will open a new ticket for:
- [ ] Delete all validated forms form Digital Journeys System
tentatively DEC 5 
Jodi is making sure this date still works for the process. Will discuss with Martha and get back to you.

**Comment by bhumin-fw** [comment] 2023-11-23 03:09
@Stella-Archer Lock SLR completely.
Delete all drafts.

SL submission will be delete from the Digital journey on **6th December, 2023**
I suggest we should wait till 6th, system will auto delete all submitted forms.

**Comment by fazil-ey** [comment] 2023-11-23 19:11
Stella to confirm Dec 6 date with jodi and if we can delete validated form or not. Currently workflow will delete all forms validated/ for validation forms.

**Comment by Stella-Archer** [comment] 2023-11-29 21:06
@bhumin-fw  Jodi would like to move the Dec 5 date to January 12th
They are planning to save all the files from the system in the event they are asked for them and need time to do that.

**Comment by Stella-Archer** [comment] 2023-12-01 00:29
I am closing this ticket and have created a new ticket #1490 to cover the January 12 retention/deletion date

**Closed** 2023-12-01 00:29 UTC
Labels: SL Review
