### ISSUE TITLE
TOOL: Form version control - Exploratory

### ISSUE THREAD

**Issue by jizhaogit** [bcgov/digital-journeys#233] opened 2022-04-29 16:22 UTC
Use GitHub repo to do forms version control

**Comment by Abuchana** [comment] 2022-05-05 20:35
Archive published versions
Internal copies of forms being built

**Comment by Stella-Archer** [comment] 2022-05-10 20:07
Have begun exploration in Miro, need input from Developers on Issues and Ideas on versioning in dev/test/prod and Input form Meghan/Alison on PIA around versioning of individual applications of telework (retention/expiry time best practices) before we consult with experts like Jennifer O

**Comment by Abuchana** [comment] 2022-05-18 15:59
The Enterprise version has built-in versioning $250/month

**Comment by HasanSifat** [comment] 2022-05-25 18:47
I have looked into the $250/month enterprise solution. Unfortunately, this is a service for a completely different propreitory software created by an American firm (Form.io). 

With Formflow.ai we are using a software platform created by AOT technologies. Given the open-source nature of our platform, there might be a very small possibility to add Form.io on top of our  Formflow.ai version. But I don't think that is possible. 

@warrenchristian1telus mentioned the enterprise solution of Form.io last week as a solution. From my research, I am assuming this would not be possible as they are two different platforms/software. But I will let Warren confirm this. 

We, in the program team, are fleshing out the future state of forms version control for all 3 environments. Will update the broader team when we have finalized our analysis. 

Also, tagging @Abuchana to this for her reference to update Ian H.

**Comment by HasanSifat** [comment] 2022-06-01 23:06
Reached out to Barry Hughes from AOT to discuss a host of features including version control. Coordinating to set up a meeting on June 08, 2022, Wednesday. Updates to follow.

**Comment by Abuchana** [comment] 2022-06-10 20:30
@HasanSifat In the interim, can you look into the manual solution Karim mentioned about using SharePoint to keep track? Then we can keep exploring a technical version.

**Comment by HasanSifat** [comment] 2022-06-13 19:29
@Abuchana Karim and AOT both referred to this manual tracking of forms and for this, we will need to maintain a specific folder to hold these downloaded forms from each environment. As a start, I can start downloading and transferring all these files into our external teams folder. 

Or we can store them in this GitHub repo. Tagging @freshjwarren in case he has anything to add.

**Comment by warrenchristian1telus** [comment] 2022-06-13 19:40
Hi @HasanSifat and @Abuchana - I recommend using a GitHub repo for this. Probably a new private one, but public may work as well. I haven't been able to test it yet, but if we use this method, rather than MS Teams, we could do things such as integrate the saved forms into the deployment pipelines and/or into FormsFlow scripts and workflows to interact with them through the site.

**Comment by Abuchana** [comment] 2022-06-13 19:44
Hi @HasanSifat and @warrenchristian1telus, it sounds as though we should try GitHub...

**Comment by HasanSifat** [comment] 2022-06-13 19:53
Okay! if we go with GitHub, we can use the new repo for our program area and incoming requests to see if we can accommodate this archiving there. 

@freshjwarren would 3 folders for dev/test/prod, do in our program area repo?

**Comment by warrenchristian1telus** [comment] 2022-06-13 21:00
Hi @HasanSifat - I think repo branches would work better for dev/test/prod (/main). It would be best to match what we're doing in the primary (this) repo, so that we can leverage the same branches, tags, etc. for both repositories. This way, we could use GitHub Actions to deploy from both repositories a bit easier, if we decide to go that route. Also, it should keep things simpler for people working with both repositories.

**Comment by HasanSifat** [comment] 2022-06-13 21:23
Hi, @freshjwarren would it be possible for you to do a demo with our team on how to set up your mentioned branches in our program area repo? We want to make sure that we are using the same structure, labels, and naming as our digital journeys dev repo here. Once we understand and have seen it done once, we should be able to take on archiving ourselves within the team.

**Comment by freshjwarren** [comment] 2022-06-13 21:33
Just to clarify, formsflow.ai (with an 's') uses the open source on-premise version of Form.io (with no 's') as a form authoring tool. Form.io also provides a hosted version as a software-as-a-service product, which includes features that are not in the open source version including versioning.

It's feasible that you could hook the hosted version of Form.io up to the on-premise version of formsflow.ai, then pay for the enterprise license, but it would likely take a significant amount of effort to hook things up that way.

**Comment by warrenchristian1telus** [comment] 2022-06-13 21:54
@freshjwarren Form.io also has an on-premise version of their Enterprise version that we could install into formsflow.ai. Although they hadn't tried that themselves, they suggested that AOT would likely have experience with (/knowledge of) doing that; and assured me that they would be happy to work with us and AOT to ensure everything works as intended.

**Comment by Abuchana** [comment] 2022-06-13 22:03
Ian Hennem has pre-approved us to get an enterprise version but he needs to know what do we get for our money, what problems will it solve, and what problems can it create?

**Comment by warrenchristian1telus** [comment] 2022-06-13 22:17
That's a good question @Abuchana - the answer is, it depends. https://www.form.io/pricing is a good place to start. However, don't pay too much attention to the $250 price tag, as that's just the starting point for one server. I believe our starting point would be closer to $500 / month / server (x3). There is also the PDF Server for $250 / mo. / server (could likely be shared between environments), and Form Manager for $150 / mo. I think we'll need to research our options to determine what we could/should handle ourselves. Potentially, we could also license some features to get a quick start, then develop tools to replace them later. Maximizing productivity in the short-term, while reducing overall costs.

**Comment by HasanSifat** [comment] 2022-07-13 17:27
Archiving through a Teams folder is currently in place where the program team is downloading the latest version of live forms in all 3 environments, daily. 

The program team will transfer this archive to a separate program area repo and continue to archive forms on that platform. 

Closing ticket as all exploratory activities is complete.

**Closed** 2022-07-13 17:27 UTC
Labels: dev - TES, devops
