### ISSUE TITLE
The user experiences that all fields get closed while filling out the form

### ISSUE THREAD

**Issue by qudsia-khan-fw** [bcgov/digital-journeys#90] opened 2022-02-22 16:24 UTC
**Background:** The user experiences that all fields get closed while filling out the form.

**Steps to Reproduce:**

1. Log in to the PSA-Digital-Journey portal on dev with valid credentials.
2. Click on "Submit New" on the "Maternity, Parental, Pre-Placement Adoption Leave and/or Allowance Application".
3. Start filling out the form. 
4. Wait a few minutes.
5. Continue to fill out the form.
**Actual Behavior:**  While filling out the form, and selecting other options in other sections, all the fields close, and any entered data is lost. 
![Screen Shot 2022-03-11 at 1.14.16 PM.png](https://images.zenhubusercontent.com/61e82c601695e01db6cd7a01/a46c4974-c242-4a48-9df9-837a52cd95e9)

**Expected Behavior:** No fields should close while the user is filling them out. All entered data should remain intact.

**Comment by matbusby-fw** [comment] 2022-02-24 22:20
Having difficulty consistently reproducing this.  
The fields are cleared sometimes, but I haven't been able to figure out which actions specifically are causing this to happen, but I don't think it's tied specifically to the checkboxes.
Placing this back into the backlog for now and will monitor the issue

**Comment by iman-jamali-fw** [comment] 2022-03-02 17:30
I was not able to reproduce the issues. Moving it back to the backlog.

**Comment by qudsia-khan-fw** [comment] 2022-03-14 14:32
@iman-jamali-fw I have updated this ticket according to what we both were able to reproduce.

**Comment by iman-jamali-fw** [comment] 2022-03-16 15:36
Taking another look at this bad boy!

**Closed as completed** 2022-03-23 17:06 UTC
Labels: 🐛 Bug, High Priority
