### ISSUE TITLE
Mat/Pat - Start date error on resubmission 

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1334] opened 2023-09-19 14:46 UTC
Supervisor receives "You must select a date between today and up to 1 month in the past, or the same date as the initial application 2023-09-23T07:00:00.000Z."  error even though the date is same as the form. 

After submitting with the changed date, the CRM ticket does not reflect the date supervisor submitted. 

**_Steps to recreate -_** 
1. Submit a mat leave application and approve it
2. Edit the mat leave start date and resubmit
3. Approve the form as Supervisor to see the error 

**_Video -_**  
Start date error in review & process tab
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-09-19%20at%207.44.02%20AM.mov?csf=1&web=1&e=GplkOm

CRM email date discrepancy 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-09-19%20at%207.55.23%20AM.mov?csf=1&web=1&e=DL624q

**Comment by bhumin-fw** [comment] 2023-09-22 18:05
@fazil-ey  @ayushdamani 
Fix start date error issue on approval and same detail update on CRM thread as well.
Changes updated on both DEV and TEST environment, and ready for testing.

**Comment by ayushdamani** [comment] 2023-09-27 16:53
Chris and Stella tested the ticket:
1. Stella submitted a mat/pat submission with Chris as her supervisor.
2. Chris was only able to edit the date till one month in the past.
3. Chris changed the start date and validated the submission.
4. The updated date was reflected in the CRM email.

**Comment by MeghanStothers** [comment] 2023-09-28 15:49
Ready for PO review

**Comment by fazil-ey** [comment] 2023-10-03 23:27
Unable to validate the form in the after submission, receiving this error even though the date is same in the submitted form and the Review and Process tab

> "You must select a date between today and up to 1 month in the past, or the same date as the initial application {{data.initialMatLeaveStartDate}}."

Video - 
https://bcgov.sharepoint.com/:v:/r/teams/03991/Shared%20Documents/Maternity%20and%20Parental%20Leave/Test%20Screenshots%20%26%20Recordings/Screen%20Recording%202023-10-03%20at%204.15.39%20PM.mov?csf=1&web=1&e=aYTxd6

**Comment by ayushdamani** [comment] 2023-10-11 16:06
I followed the steps provided in the ticket, and I was not able to reproduce the issue that Fazil faced.
Moving to PO.

**Comment by Stella-Archer** [comment] 2023-10-12 18:28
dates are updating in the CRM ticket correctly now
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWN2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba545fef2598359dc704883d2006542757db2240/image.png)
how ever I did NOT get an email when I updated from DJ or CRM

**Comment by fazil-ey** [comment] 2023-10-13 18:15
Able to approve resubmissions with edits without issues

**Closed** 2023-10-13 18:15 UTC
Labels: Bug, Mat/Pat, MVP, Test failed
