### ISSUE TITLE
Mat/Pat - Bug in CRM on Resubmission

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#1372] opened 2023-10-05 16:52 UTC
When a mat/pat form is edited and resubmitted, the new thread in CRM does not have the updated date. The pdf however in CRM has the updated date and the submitted

Ticket reference id - 231005-000000
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMElNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--566f2d74035b68a9df43d0be58bd9b55f7408217/MicrosoftTeams-image.png)

**Comment by bhumin-fw** [comment] 2023-10-05 18:00
@fazil-ey 
Could you please share the exact steps to reproduce it?
I assume, 
Form submitted -> approved (CRM created) -> edit by user (update date) and resubmit -> reapproved again (CRM Update).

**Comment by fazil-ey** [comment] 2023-10-12 18:19
As per latest testing we have not observed this bug. The dates are changing when the ticket is updated by applicant & supervisor and resubmitted. 

@bhumin-fw  can double check and move it to QA/PO

**Comment by MeghanStothers** [comment] 2023-10-13 15:51
Looks good, cannot reproduce this bug.

**Comment by MeghanStothers** [comment] 2023-10-16 15:49
One more test and if there isn't an issue, we will close this ticket.

**Comment by fazil-ey** [comment] 2023-10-18 23:12
This was not noticed in multiple tests by stella and team.  Closing for now but will keep an eye out

**Closed** 2023-10-18 23:12 UTC
Labels: Mat/Pat, MVP
