### ISSUE TITLE
1.10: Emails on form submit

### ISSUE THREAD

**Issue by fazil-ey** [bcgov/digital-journeys#730] opened 2022-11-17 04:47 UTC
**User Story**
As PSA or LDB I want to receive an email on submission of 1.10 forms so that we are informed about the incident and can initiate the process for resolution of the complaint. 

**Acceptance Criteria**

- [x] if not LDB, email sent to PSA mailbox (email to be added)
- [x] If LDB email sent to LDB mailbox
- [x] Form should be sent as a PDF
- [x] email to be sent to recipient
- [x] email to be sent to complainant themselves  
- [x] Once email has been sent set the form status to Completed
~- [ ] Once the form has been submitted set the form status to Submitted~

Refer to the below ticket description for LDB and PSA mail conditions.
https://app.zenhub.com/workspaces/digital-journeys-61c10fe84c8bcb001491c5f5/issues/bcgov/digital-journeys/784

**Comment by fazil-ey** [comment] 2022-11-24 19:36
Have a skeleton setup with placeholder emails

**Comment by bhumin-fw** [comment] 2022-12-05 12:57
@fazil-ey 
Do we have content ready that will send in an email?
**Email 1**: to Recipient
title, emailbody required, attachment name (optional)
**Email 2**: to complainant themselves
title, emailBody , attachment name (optional)

**Comment by morezooomm** [comment] 2022-12-05 21:04
Fazil,

My proposed answers are embedded below. I have also attached the latest version of the form, as of Dec 5.

I am open to suggestions from others if we could use a better email title or content.
Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment] 2022-12-06 13:14
@morezooomm Thank you for your quick action here.

@MissionT @fazil-ey 
I have added a new camunda workflow "**1.10 Complaint Intake Form - v0.1**".
It will send 3 emails.
1. PSA or LDB inbox (For now I have added my email for review). It will decide based on form param "LDB employee in the written complaint section".
2. To the Submitter
3. To the Recipient

**Contact and title for the email that sends to PSA or LDB mailbox are required here.** (I have added temp content and title to it for this workflow)

Note: Please attach it to 1.10 form for testing. (I have tested and removed for now)

cc: @iman-jamali-fw @simensma-fresh

**Comment by bhumin-fw** [comment] 2022-12-06 17:20
@fazil-ey 
Changes are there on DEV.
When you start testing please attach workflow "1.10 Complaint Intake Form - v0.1" with the form. Please drop queries if you have any on the testing email.
cc: @MissionT @simensma-fresh @iman-jamali-fw

**Comment by bhumin-fw** [comment] 2022-12-14 13:48
Updated form Name : **Bullying and Harassment Complaint Form Article 1.10**
Updated workflow name: **bullying-and-harassment-complaint-article-1-10**

Form and workflow are deployed on DEV and TEST.
Note: For the PSA and LDB mailbox I have added my ey email for testing. Please do let me know if you want to add any other email here for your testing purpose.

**Comment by morezooomm** [comment] 2022-12-14 14:24
We should likely update the names below to keep them consistent with the form name, which is “Bully / Misuse of Authority Complaint Form (Article 1.10)”

Note we removed harassment from the name because that falls under Article 1.09, not Article 1.10.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment] 2022-12-14 15:49
@morezooomm 
I have added the subject as "Bully / Misuse of Authority Complaint Form (Article 1.10)" for all the emails. It is available to test.
It will send an email on "written complaint" and "recipient" emails. You can test it on DEV or TEST environment.

above mentioned was form title. Let me check with Iman and Fazil to change it, as that is connected with a couple of other tasks carried out by Iman.

**Comment by bhumin-fw** [comment] 2022-12-14 16:38
@morezooomm 
Just change "Bully" to "Bullying", it is again ready to test on DEV and TEST.

**Comment by fazil-ey** [comment] 2022-12-15 18:45
@morezooomm to provide the PSA mailbox address and then @morezooomm  can test this out

**Comment by morezooomm** [comment] 2022-12-15 19:07
The new email address is ***@***.******@***.***>.

That IDIR is currently inactive, but I hope to reactive the IDIR this afternoon.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment] 2022-12-16 16:01
@fazil-ey I have updated the mail to PSA.RegistrarIntake@gov.bc.ca.

**Comment by fazil-ey** [comment] 2022-12-16 21:58
The recipient & complainant are receiving emails successfully

**Comment by fazil-ey** [comment] 2022-12-21 00:31
Change email sent to PSA complainant - 

“Attached is a copy of the complaint you just submitted to the Public Service Agency (PSA) regarding a bullying / misuse of authority complaint under article 1.10 of the collective agreement. You may ask your union representative at any time for an update on the status of a review or investigation arising from your complaint.”

**Comment by morezooomm** [comment] 2022-12-21 11:47
Thanks.   Looks good.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment] 2022-12-21 15:35
@fazil-ey @morezooomm 
Content for complainant change if they are PSA employees. Else it will send the original content if LDB employee.
Changes updated on the TEST environment.

**Comment by morezooomm** [comment] 2022-12-21 15:40
The original content should be for PSA, as that will cover the majority of complaints and the material is already provided.  Content should change for LDB employees, but I don’t believe we have that specific content from LDB yet.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by fazil-ey** [comment] 2023-01-17 17:29
Emails have been tested - everyone does receive the email as expected. 

However, the form status for submitted forms is "Completed" & not "Submitted". @bhumin-fw  can you confirm is that okay

**Comment by morezooomm** [comment] 2023-01-17 17:38
My preference would be to label these as “Submitted” rather than “Completed” as it will provide better consistency with other content on the site and avoid possible confusion for users.  Thanks.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment] 2023-01-17 18:26
@fazil-ey @morezooomm 
In the process "Submitted" allow user to edit form, and "completed" means no further action allowed. We can change it to something like "Put-Forward", "Registered", etc.

To allow "submitted" in this form required to set new flow in the web repository. If that's the case then let's a new ticket and handle this change.

**Comment by morezooomm** [comment] 2023-01-17 18:44
Sorry, I may have been unclear on the question raised.

On the DJ Portal, there is a tab for “Submitted” forms, and when you click on the tab, the heading that appears says “Submitted” forms, so I thought the status in the Status column should also say “Submitted” rather than “Completed”, for consistency.  If that is not possible, then I would leave the status in the Status column as “Completed”.

Whether we use “Submitted” or “Completed”, that status should NOT allow users to make further changes to the form; they should only be allowed to make further changes to forms in “Draft” mode.

Hope this clarification helps but let me know if there are further questions.  Cheers!

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by bhumin-fw** [comment] 2023-01-17 19:09
@morezooomm 
That seems clear already Don. Thanks for the confirmation.

For more detail on your point:
"Submitted forms" tab shows all forms submitted by you. Different forms will have different status. like "New", "Resubmit", "Approved", "Rejected", "Accepted", "Submitted" and "Completed" based on form that you are submitting.
Here other than "Completed" all forms allows user to edit, Form status "new", "Resubmit" and "Submitted" allow to edit full form. "Approved" and "rejected" allow to edit partial form.

The best part of such code is, we can change status as per our requirement, but that required little to average developer side efforts. because those change needs to apply for selected form only. That's why I proposed to add new ticket if that is a required changes on the business side.

If status for the form is not "New", "Resubmit", "Approved", "Rejected", and "Submitted" then it's by default not allow you to edit. Which means if we introduce any new status like "Registered" it won't be editable. And that can change in form-flow itself and no new ticket required for the same (this is a very small change and can be done in "formedit" mode).

I hope these comments helps you to take a final decision. like move ticket to prod or add new ticket to make required change based business requirement side.

**Comment by fazil-ey** [comment] 2023-01-18 16:54
As suggested "Completed" status is good for now.

**Comment by morezooomm** [comment] 2023-01-18 17:02
Agreed.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by fazil-ey** [comment] 2023-01-25 17:11
@bhumin-fw to setup the LDB emails to be sent to ![image.png](https://images.zenhubusercontent.com/62e986a3ff9c07df27cce462/09c83e1a-1728-4b6f-bd0f-9c656b128e47)

**Comment by bhumin-fw** [comment] 2023-01-25 17:20
@fazil-ey 
Setup employee.relations@bcldb.com email as LDB mailbox email. It's available to test on DEV and TEST both.

**Comment by fazil-ey** [comment] 2023-01-25 17:22
@morezooomm can you test by submitting an LDB form and confirming with Lindsey if it was received?

**Comment by MissionT** [comment] 2023-01-25 17:47
Tested the PDF and everything downloaded! All good.

**Comment by morezooomm** [comment] 2023-01-26 17:01
Fazil,

I submitted a test LDB complaint and Lindsey confirmed she received it, so the email they provided is working.

Don Smallwood, Director of Investigations & Intake
Employee Relations Division | BC Public Service Agency
167 Lorne Street | Kamloops BC | V2C 1V9
Office: (778) 694-7600 | Mobile: 250-938-5141
Living with gratitude and respect on the unceded territory of the Splatsin

**Comment by MeghanStothers** [comment] 2023-03-08 17:24
OKay to close this one.

**Closed** 2023-03-08 17:24 UTC
Labels: Dev - TES/EY, PO Approved, 1.10 Formal Complaints
