### ISSUE TITLE
Create Production Environment

### ISSUE THREAD

**Issue by DonMoffatt** [bcgov/digital-journeys#222] opened 2022-04-25 16:24 UTC
As a forms designer, I need to be able to push the form to an environment where it can be seen by the wider government in order to test and use it by end users.

**Comment by Abuchana** [comment] 2022-04-28 20:28
Aim for May 20th 
Warren inquiring with Phill

**Comment by warrenchristian1telus** [comment] 2022-04-29 17:32
The production environment is live. I'm looking into any outstanding transfers / migrations that may be required. There is currently no content, but it otherwise seems to be functioning as expected.

https://digital-journeys.apps.silver.devops.gov.bc.ca

**Comment by DonMoffatt** [comment] 2022-05-06 18:47
We will only know whether this is functioning when we have tested forms in it.

**Comment by Stella-Archer** [comment] 2022-05-09 15:57
Monday May 9th - still getting 'No forms found'

**Comment by warrenchristian1telus** [comment] 2022-05-09 17:57
@Stella-Archer @DonMoffatt - I'm seeing the Telework form in production. Maybe this is due to a permissions issue. I'll see if I can spot a discrepancy in KeyCloak.

![image](https://user-images.githubusercontent.com/70002196/167469198-50050849-6bb1-4ede-b384-388ca7f45f7b.png)

**Comment by warrenchristian1telus** [comment] 2022-05-09 18:37
@Stella-Archer @DonMoffatt I think I've found and resolved the permissions issue in production. Please test again and let me know if you can now see the Telework Agreement form.

**Comment by warrenchristian1telus** [comment] 2022-05-09 22:39
Found an issue with forms-flow-bpm-85-z4xpf: CrashLoopBackOff

Investigating the root cause.

Moving this back to in progress until resolved.

**Comment by warrenchristian1telus** [comment] 2022-05-13 21:28
@iman-jamali-fw Once the deployment is completed with #232, please ensure that the latest Telework Agreement form updates are in production, then we can move this to QA for review.

**Closed** 2022-05-18 15:58 UTC
Labels: dev - TES
